apiVersion: v1
kind: Secret
metadata:
    name: vkbot-secrets
    namespace: vkbot
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:pVfBMrsXM5AX,iv:Rxbw7ZrgM9Oxk6NQz8/SvNyF1kE9L6jeVde6WBwGVzA=,tag:AYmSaIBrBFwJIjYRnD0+kw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BIf4SlACg7oxHSvBOQ==,iv:BflroOaboP53yRq5QWTmgacFSxRlXgBfPITeNLo6HUo=,tag:04suwYot3Q0WWCI+3ivQnQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:W6DJg4I=,iv:BcTcLfE7vCldkhAJWJSkxzprPjikpOidzic/nLKTE3s=,tag:A2O4gX18z2nbiO0m0KfI6Q==,type:str]
    VK_TOKEN: ENC[AES256_GCM,data:PkCaXGGrbJeqvcUs5Q==,iv:mbOiMSXNc7nGQZ1pafmecngRYouco3tLGD6cLtDTL0I=,tag:5K0YJPzUcmJwEz6xROwfTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wepx4s7spgq4u8njv4xnph3k488mwf60m30vlzz0yfh4p4pvduds3kgz0q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WEYzancvSVptQUFjdzdy
            cE1pK2lrenFkTDhjbXVIeVF2VDMxdkZEYkhBCkNVRlpUUFFDYnA4bjZEaGJHUlpK
            Ujk0YmhCWEJLanUrMGxXM0ZSTWI1MTgKLS0tIFo0aFdOYytpQXZYTER3TUVpUzc0
            S3FwV0hiZEFPdExwWlMwM2Z0MGJHam8KjfTBczuISattj6/0lwrKLF3w+dDGlkD3
            CwhQtg6LWHdv+RCgl9PWTHCNbFlE0E6xDdwZWVUm+VTtvETn+nQJaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T09:08:55Z"
    mac: ENC[AES256_GCM,data:lJhuuorzZSd1u/yQl3xIUMOog/FywAF3Tlmm7glX2R/9wGiMKJ9hceTEROpNy8X59T7QMU/jbvPUu4zm0tfSk2vtRS76XXJ+pBAP2fsYYu+FCR5RQgqEjiphUznN0MBMKtYz9Ds1rfRKsJecoYaIiAj5CyNpqX7APhzsM8mGJm8=,iv:z4IsiliZpYFs9522j/N4Ff2qowt0RwK1v15ZJ+m1g6w=,tag:HpOMFGNlKKq8FVEWSRIsUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
