apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vkbot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ayne272/vkpybot.git
    targetRevision: main
    path: k8s
    plugin:
      name: argocd-vault-plugin-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: vkbot
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
